version: "39"

services:
  db:
    image: postgres:17
    container_name: uchomps_dev_db
    restart: always
    env_file: ./.env.db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/0-init-db.sql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
