name: Run Server Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: uchomp_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for Postgres..."
          until pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done

      - name: Set up schema and seed data
        working-directory: server
        env:
          PGPASSWORD: password
        run: |
          psql -h localhost -U postgres -d uchomp_dev -f db/init-db.sql
          psql -h localhost -U postgres -d uchomp_dev -f db/schema.sql
          psql -h localhost -U postgres -d uchomp_dev -f db/seed.sql

      - name: Run tests
        working-directory: server
        env:
          DATABASE_URL: postgresql://neondb_owner:password@localhost:5432/uchomp_dev
        run: npm run test
